[package]
name = "starks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.11.0"
primitive-types = "0.12.1"
rand = "0.8.5"
rs_merkle = "1.4.1"
sha256 = "1.1.4"
